import React from 'react';
import { LegalLayout } from '../components/layout/LegalLayout';

export const Terms: React.FC = () => {
  return (
    <LegalLayout>
      <div className="prose prose-invert max-w-none">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-slate-400 text-sm mb-8">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <div className="space-y-6 text-slate-300">
          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">1. Agreement to Terms</h2>
            <p>
              By accessing or using Apex SEO ("Service"), you agree to be bound by these Terms of Service ("Terms"). 
              If you disagree with any part of these terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">2. Description of Service</h2>
            <p>
              Apex SEO is a Software as a Service (SaaS) platform that provides automated content generation, 
              SEO optimization, and content scheduling services. The Service uses artificial intelligence to 
              generate content based on your specifications.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">3. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all 
              activities that occur under your account. You agree to notify us immediately of any unauthorized 
              use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">4. Subscription and Billing</h2>
            <p>
              The Service is provided on a subscription basis. By subscribing, you agree to pay the fees 
              associated with your chosen plan. Subscriptions automatically renew unless canceled. You may 
              cancel your subscription at any time through your account settings or by contacting support.
            </p>
            <p className="mt-3">
              All fees are non-refundable except as required by law. We reserve the right to change our 
              pricing with 30 days' notice to existing subscribers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">5. AI Generated Content</h2>
            <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-4 my-4">
              <p className="text-amber-300 font-medium mb-2">Important Notice:</p>
              <p>
                You acknowledge that content generated by Apex SEO is created using Artificial Intelligence. 
                Apex SEO is not liable for factual inaccuracies, errors, or omissions in AI-generated content. 
                You are solely responsible for reviewing, editing, and verifying all content before publication. 
                You agree to use the Service in compliance with all applicable laws and regulations.
              </p>
            </div>
            <p>
              While we strive to provide accurate and high-quality content, AI-generated content may contain 
              errors or inaccuracies. It is your responsibility to ensure that all content meets your standards 
              and complies with applicable laws before publishing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside ml-4 space-y-2 mt-2">
              <li>Use the Service for any illegal purpose or in violation of any laws</li>
              <li>Generate content that is defamatory, harassing, or infringes on intellectual property rights</li>
              <li>Attempt to reverse engineer, decompile, or disassemble the Service</li>
              <li>Use automated systems to access the Service in a manner that sends more requests than a human could reasonably produce</li>
              <li>Share your account credentials with others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">7. Intellectual Property</h2>
            <p>
              The Service and its original content, features, and functionality are owned by Apex SEO and 
              are protected by international copyright, trademark, and other intellectual property laws. 
              Content generated through the Service belongs to you, subject to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Apex SEO shall not be liable for any indirect, 
              incidental, special, consequential, or punitive damages, or any loss of profits or revenues, 
              whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible 
              losses resulting from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">9. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service immediately, without prior 
              notice, for conduct that we believe violates these Terms or is harmful to other users, us, or 
              third parties. Upon termination, your right to use the Service will cease immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any material 
              changes by posting the new Terms on this page and updating the "Last updated" date. Your 
              continued use of the Service after such changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-8 mb-4">11. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mt-2">
              Email: support@apex-seo.app<br />
              Address: 123 Business Street, Suite 100, City, State 12345, United States
            </p>
          </section>
        </div>
      </div>
    </LegalLayout>
  );
};
